<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit978a9dc8ac0665dbc8294fb48efb974f
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'k' => 
        array (
            'kornrunner\\' => 11,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
        ),
        'C' => 
        array (
            'Cryptum\\NFT\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'kornrunner\\' => 
        array (
            0 => __DIR__ . '/..' . '/kornrunner/keccak/src',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Cryptum\\NFT\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit978a9dc8ac0665dbc8294fb48efb974f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit978a9dc8ac0665dbc8294fb48efb974f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit978a9dc8ac0665dbc8294fb48efb974f::$classMap;

        }, null, ClassLoader::class);
    }
}
